// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: site/ani4h/shared/proto/user.proto
// Protobuf Java Version: 4.30.0

package site.ani4h.shared;

public final class UserOuterClass {
  private UserOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      UserOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetUsersByIdsReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetUsersByIdsReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
     * @return A list containing the ids.
     */
    java.util.List<java.lang.Integer> getIdsList();
    /**
     * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
     * @return The count of ids.
     */
    int getIdsCount();
    /**
     * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
     * @param index The index of the element to return.
     * @return The ids at the given index.
     */
    int getIds(int index);
  }
  /**
   * Protobuf type {@code GetUsersByIdsReq}
   */
  public static final class GetUsersByIdsReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GetUsersByIdsReq)
      GetUsersByIdsReqOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        GetUsersByIdsReq.class.getName());
    }
    // Use GetUsersByIdsReq.newBuilder() to construct.
    private GetUsersByIdsReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetUsersByIdsReq() {
      ids_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return site.ani4h.shared.UserOuterClass.internal_static_GetUsersByIdsReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return site.ani4h.shared.UserOuterClass.internal_static_GetUsersByIdsReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              site.ani4h.shared.UserOuterClass.GetUsersByIdsReq.class, site.ani4h.shared.UserOuterClass.GetUsersByIdsReq.Builder.class);
    }

    public static final int IDS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList ids_ =
        emptyIntList();
    /**
     * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
     * @return A list containing the ids.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getIdsList() {
      return ids_;
    }
    /**
     * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
     * @return The count of ids.
     */
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
     * @param index The index of the element to return.
     * @return The ids at the given index.
     */
    public int getIds(int index) {
      return ids_.getInt(index);
    }
    private int idsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getIdsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(idsMemoizedSerializedSize);
      }
      for (int i = 0; i < ids_.size(); i++) {
        output.writeInt32NoTag(ids_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(ids_.getInt(i));
        }
        size += dataSize;
        if (!getIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        idsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof site.ani4h.shared.UserOuterClass.GetUsersByIdsReq)) {
        return super.equals(obj);
      }
      site.ani4h.shared.UserOuterClass.GetUsersByIdsReq other = (site.ani4h.shared.UserOuterClass.GetUsersByIdsReq) obj;

      if (!getIdsList()
          .equals(other.getIdsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIdsCount() > 0) {
        hash = (37 * hash) + IDS_FIELD_NUMBER;
        hash = (53 * hash) + getIdsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(site.ani4h.shared.UserOuterClass.GetUsersByIdsReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetUsersByIdsReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetUsersByIdsReq)
        site.ani4h.shared.UserOuterClass.GetUsersByIdsReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return site.ani4h.shared.UserOuterClass.internal_static_GetUsersByIdsReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return site.ani4h.shared.UserOuterClass.internal_static_GetUsersByIdsReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                site.ani4h.shared.UserOuterClass.GetUsersByIdsReq.class, site.ani4h.shared.UserOuterClass.GetUsersByIdsReq.Builder.class);
      }

      // Construct using site.ani4h.shared.UserOuterClass.GetUsersByIdsReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ids_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return site.ani4h.shared.UserOuterClass.internal_static_GetUsersByIdsReq_descriptor;
      }

      @java.lang.Override
      public site.ani4h.shared.UserOuterClass.GetUsersByIdsReq getDefaultInstanceForType() {
        return site.ani4h.shared.UserOuterClass.GetUsersByIdsReq.getDefaultInstance();
      }

      @java.lang.Override
      public site.ani4h.shared.UserOuterClass.GetUsersByIdsReq build() {
        site.ani4h.shared.UserOuterClass.GetUsersByIdsReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public site.ani4h.shared.UserOuterClass.GetUsersByIdsReq buildPartial() {
        site.ani4h.shared.UserOuterClass.GetUsersByIdsReq result = new site.ani4h.shared.UserOuterClass.GetUsersByIdsReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(site.ani4h.shared.UserOuterClass.GetUsersByIdsReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          ids_.makeImmutable();
          result.ids_ = ids_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof site.ani4h.shared.UserOuterClass.GetUsersByIdsReq) {
          return mergeFrom((site.ani4h.shared.UserOuterClass.GetUsersByIdsReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(site.ani4h.shared.UserOuterClass.GetUsersByIdsReq other) {
        if (other == site.ani4h.shared.UserOuterClass.GetUsersByIdsReq.getDefaultInstance()) return this;
        if (!other.ids_.isEmpty()) {
          if (ids_.isEmpty()) {
            ids_ = other.ids_;
            ids_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureIdsIsMutable();
            ids_.addAll(other.ids_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readInt32();
                ensureIdsIsMutable();
                ids_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureIdsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  ids_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList ids_ = emptyIntList();
      private void ensureIdsIsMutable() {
        if (!ids_.isModifiable()) {
          ids_ = makeMutableCopy(ids_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
       * @return A list containing the ids.
       */
      public java.util.List<java.lang.Integer>
          getIdsList() {
        ids_.makeImmutable();
        return ids_;
      }
      /**
       * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
       * @return The count of ids.
       */
      public int getIdsCount() {
        return ids_.size();
      }
      /**
       * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
       * @param index The index of the element to return.
       * @return The ids at the given index.
       */
      public int getIds(int index) {
        return ids_.getInt(index);
      }
      /**
       * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
       * @param index The index to set the value at.
       * @param value The ids to set.
       * @return This builder for chaining.
       */
      public Builder setIds(
          int index, int value) {

        ensureIdsIsMutable();
        ids_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
       * @param value The ids to add.
       * @return This builder for chaining.
       */
      public Builder addIds(int value) {

        ensureIdsIsMutable();
        ids_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
       * @param values The ids to add.
       * @return This builder for chaining.
       */
      public Builder addAllIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ids_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ids = 1 [json_name = "ids"];</code>
       * @return This builder for chaining.
       */
      public Builder clearIds() {
        ids_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetUsersByIdsReq)
    }

    // @@protoc_insertion_point(class_scope:GetUsersByIdsReq)
    private static final site.ani4h.shared.UserOuterClass.GetUsersByIdsReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new site.ani4h.shared.UserOuterClass.GetUsersByIdsReq();
    }

    public static site.ani4h.shared.UserOuterClass.GetUsersByIdsReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetUsersByIdsReq>
        PARSER = new com.google.protobuf.AbstractParser<GetUsersByIdsReq>() {
      @java.lang.Override
      public GetUsersByIdsReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetUsersByIdsReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetUsersByIdsReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public site.ani4h.shared.UserOuterClass.GetUsersByIdsReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PublicUserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PublicUserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string first_name = 2 [json_name = "firstName"];</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string first_name = 2 [json_name = "firstName"];</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string last_name = 3 [json_name = "lastName"];</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 3 [json_name = "lastName"];</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string user_name = 4 [json_name = "userName"];</code>
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <code>string user_name = 4 [json_name = "userName"];</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string system_role = 6 [json_name = "systemRole"];</code>
     * @return The systemRole.
     */
    java.lang.String getSystemRole();
    /**
     * <code>string system_role = 6 [json_name = "systemRole"];</code>
     * @return The bytes for systemRole.
     */
    com.google.protobuf.ByteString
        getSystemRoleBytes();
  }
  /**
   * Protobuf type {@code PublicUserInfo}
   */
  public static final class PublicUserInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PublicUserInfo)
      PublicUserInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        PublicUserInfo.class.getName());
    }
    // Use PublicUserInfo.newBuilder() to construct.
    private PublicUserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PublicUserInfo() {
      firstName_ = "";
      lastName_ = "";
      userName_ = "";
      systemRole_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return site.ani4h.shared.UserOuterClass.internal_static_PublicUserInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return site.ani4h.shared.UserOuterClass.internal_static_PublicUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              site.ani4h.shared.UserOuterClass.PublicUserInfo.class, site.ani4h.shared.UserOuterClass.PublicUserInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object firstName_ = "";
    /**
     * <code>string first_name = 2 [json_name = "firstName"];</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string first_name = 2 [json_name = "firstName"];</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lastName_ = "";
    /**
     * <code>string last_name = 3 [json_name = "lastName"];</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string last_name = 3 [json_name = "lastName"];</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_NAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userName_ = "";
    /**
     * <code>string user_name = 4 [json_name = "userName"];</code>
     * @return The userName.
     */
    @java.lang.Override
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string user_name = 4 [json_name = "userName"];</code>
     * @return The bytes for userName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYSTEM_ROLE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object systemRole_ = "";
    /**
     * <code>string system_role = 6 [json_name = "systemRole"];</code>
     * @return The systemRole.
     */
    @java.lang.Override
    public java.lang.String getSystemRole() {
      java.lang.Object ref = systemRole_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        systemRole_ = s;
        return s;
      }
    }
    /**
     * <code>string system_role = 6 [json_name = "systemRole"];</code>
     * @return The bytes for systemRole.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSystemRoleBytes() {
      java.lang.Object ref = systemRole_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemRole_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(firstName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, lastName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, userName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(systemRole_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, systemRole_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(firstName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, lastName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, userName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(systemRole_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, systemRole_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof site.ani4h.shared.UserOuterClass.PublicUserInfo)) {
        return super.equals(obj);
      }
      site.ani4h.shared.UserOuterClass.PublicUserInfo other = (site.ani4h.shared.UserOuterClass.PublicUserInfo) obj;

      if (getId()
          != other.getId()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (!getSystemRole()
          .equals(other.getSystemRole())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + SYSTEM_ROLE_FIELD_NUMBER;
      hash = (53 * hash) + getSystemRole().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static site.ani4h.shared.UserOuterClass.PublicUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(site.ani4h.shared.UserOuterClass.PublicUserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PublicUserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PublicUserInfo)
        site.ani4h.shared.UserOuterClass.PublicUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return site.ani4h.shared.UserOuterClass.internal_static_PublicUserInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return site.ani4h.shared.UserOuterClass.internal_static_PublicUserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                site.ani4h.shared.UserOuterClass.PublicUserInfo.class, site.ani4h.shared.UserOuterClass.PublicUserInfo.Builder.class);
      }

      // Construct using site.ani4h.shared.UserOuterClass.PublicUserInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        firstName_ = "";
        lastName_ = "";
        userName_ = "";
        systemRole_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return site.ani4h.shared.UserOuterClass.internal_static_PublicUserInfo_descriptor;
      }

      @java.lang.Override
      public site.ani4h.shared.UserOuterClass.PublicUserInfo getDefaultInstanceForType() {
        return site.ani4h.shared.UserOuterClass.PublicUserInfo.getDefaultInstance();
      }

      @java.lang.Override
      public site.ani4h.shared.UserOuterClass.PublicUserInfo build() {
        site.ani4h.shared.UserOuterClass.PublicUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public site.ani4h.shared.UserOuterClass.PublicUserInfo buildPartial() {
        site.ani4h.shared.UserOuterClass.PublicUserInfo result = new site.ani4h.shared.UserOuterClass.PublicUserInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(site.ani4h.shared.UserOuterClass.PublicUserInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.firstName_ = firstName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.lastName_ = lastName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.userName_ = userName_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.systemRole_ = systemRole_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof site.ani4h.shared.UserOuterClass.PublicUserInfo) {
          return mergeFrom((site.ani4h.shared.UserOuterClass.PublicUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(site.ani4h.shared.UserOuterClass.PublicUserInfo other) {
        if (other == site.ani4h.shared.UserOuterClass.PublicUserInfo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getSystemRole().isEmpty()) {
          systemRole_ = other.systemRole_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                firstName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                lastName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                userName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 50: {
                systemRole_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string first_name = 2 [json_name = "firstName"];</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string first_name = 2 [json_name = "firstName"];</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string first_name = 2 [json_name = "firstName"];</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        firstName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2 [json_name = "firstName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        firstName_ = getDefaultInstance().getFirstName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2 [json_name = "firstName"];</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        firstName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string last_name = 3 [json_name = "lastName"];</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_name = 3 [json_name = "lastName"];</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_name = 3 [json_name = "lastName"];</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lastName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3 [json_name = "lastName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        lastName_ = getDefaultInstance().getLastName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3 [json_name = "lastName"];</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lastName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string user_name = 4 [json_name = "userName"];</code>
       * @return The userName.
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_name = 4 [json_name = "userName"];</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_name = 4 [json_name = "userName"];</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 4 [json_name = "userName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        userName_ = getDefaultInstance().getUserName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 4 [json_name = "userName"];</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object systemRole_ = "";
      /**
       * <code>string system_role = 6 [json_name = "systemRole"];</code>
       * @return The systemRole.
       */
      public java.lang.String getSystemRole() {
        java.lang.Object ref = systemRole_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          systemRole_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string system_role = 6 [json_name = "systemRole"];</code>
       * @return The bytes for systemRole.
       */
      public com.google.protobuf.ByteString
          getSystemRoleBytes() {
        java.lang.Object ref = systemRole_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          systemRole_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string system_role = 6 [json_name = "systemRole"];</code>
       * @param value The systemRole to set.
       * @return This builder for chaining.
       */
      public Builder setSystemRole(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        systemRole_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string system_role = 6 [json_name = "systemRole"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSystemRole() {
        systemRole_ = getDefaultInstance().getSystemRole();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string system_role = 6 [json_name = "systemRole"];</code>
       * @param value The bytes for systemRole to set.
       * @return This builder for chaining.
       */
      public Builder setSystemRoleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        systemRole_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PublicUserInfo)
    }

    // @@protoc_insertion_point(class_scope:PublicUserInfo)
    private static final site.ani4h.shared.UserOuterClass.PublicUserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new site.ani4h.shared.UserOuterClass.PublicUserInfo();
    }

    public static site.ani4h.shared.UserOuterClass.PublicUserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PublicUserInfo>
        PARSER = new com.google.protobuf.AbstractParser<PublicUserInfo>() {
      @java.lang.Override
      public PublicUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PublicUserInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PublicUserInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public site.ani4h.shared.UserOuterClass.PublicUserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetUsersByIdsReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetUsersByIdsReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicUserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PublicUserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"site/ani4h/shared/proto/user.proto\"$\n\020" +
      "GetUsersByIdsReq\022\020\n\003ids\030\001 \003(\005R\003ids\"\232\001\n\016P" +
      "ublicUserInfo\022\016\n\002id\030\001 \001(\005R\002id\022\035\n\nfirst_n" +
      "ame\030\002 \001(\tR\tfirstName\022\033\n\tlast_name\030\003 \001(\tR" +
      "\010lastName\022\033\n\tuser_name\030\004 \001(\tR\010userName\022\037" +
      "\n\013system_role\030\006 \001(\tR\nsystemRole29\n\004User\022" +
      "1\n\013GetUserById\022\021.GetUsersByIdsReq\032\017.Publ" +
      "icUserInfoB\023\n\021site.ani4h.sharedb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetUsersByIdsReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetUsersByIdsReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetUsersByIdsReq_descriptor,
        new java.lang.String[] { "Ids", });
    internal_static_PublicUserInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PublicUserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PublicUserInfo_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "UserName", "SystemRole", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
