import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/layout/topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <div className="">
        <header className="absolute top-0 z-50 w-full">
            <TopBar/>
        </header>
        <main className={"relative"}>
            {children}
        </main>
        <footer className={"mt-20"}>
            <div className={"divider"}></div>
            <div className={"flex justify-evenly"}>
                <div className={" space-y-2"}>
                    <p>Thỏa thuận và Điều khoản</p>
                    <p className={"opacity-50"}>Chính sách bảo mật</p>
                    <p className={"opacity-50"}>Thỏa thuận và Điều khoản</p>
                    <p className={"opacity-50"}>Chính sách Cookie</p>
                </div>
                <div className={" space-y-2"}>
                    <p>Hỗ trợ và phản hồi</p>
                    <p className={"opacity-50"}>Phản hồi1</p>
                    <p className={"opacity-50"}>Câu hỏi thường gặp</p>
                </div>
                <div className={" space-y-2"}>
                    <p>Thông tin về chúng tôi</p>
                    <p className={"opacity-50"}>Gia nhập cùng chúng tôi</p>
                    <p className={"opacity-50"}>Liên hệ với chúng tôi</p>

                </div>
            </div>
            <div className={"divider"}></div>
        </footer>
    </div>
    </body>
    </html>
  );
}
