import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/layout/topbar";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="">
          <header className="absolute top-0 z-50 w-full">
              <TopBar/>
          </header>
          <main className={"relative"}>
              {children}
          </main>
          <footer className={"mt-20"}>
              <div className={"divider"}></div>
              <div className={"flex justify-evenly"}>
                  <div className={" space-y-2"}>
                      <p>Thỏa thuận và Điều khoản</p>
                      <p className={"opacity-50"}>Chính sách bảo mật</p>
                      <p className={"opacity-50"}>Thỏa thuận và Điều khoản</p>
                      <p className={"opacity-50"}>Chính sách Cookie</p>
                  </div>
                  <div className={" space-y-2"}>
                      <p>Hỗ trợ và phản hồi</p>
                      <p className={"opacity-50"}>Phản hồi1</p>
                      <p className={"opacity-50"}>Câu hỏi thường gặp</p>
                  </div>
                  <div className={" space-y-2"}>
                      <p>Thông tin về chúng tôi</p>
                      <p className={"opacity-50"}>Gia nhập cùng chúng tôi</p>
                      <p className={"opacity-50"}>Liên hệ với chúng tôi</p>
                      {/*<a data-v-38b1e831="" className="item"*/}
                      {/*   href="https://accounts.google.com/o/oauth2/v2/auth?client_id=1080357856969-q0fgj24pd2csvqdm0ksg61msuojir4jj.apps.googleusercontent.com&amp;redirect_uri=https%3A%2F%2Fcloud.vmoscloud.com%2Flogin%2Fgoogle&amp;response_type=token&amp;scope=openid%20profile%20email&amp;state="><img*/}
                      {/*    data-v-38b1e831=""*/}
                      {/*    src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADEAAAAwCAYAAAC4wJK5AAAAAXNSR0IArs4c6QAACMVJREFUaEPFWg1wVNUV/u7+b0L+CampMCQkDTXYBCvUYJ0Siy1VqDZN0TBjDCIto/JToMXaQkFQRqeVgD9VZyhYRxxLK6K2KmVKRM1ASkoAZSoNkESIIT+bDUl2N7v73i3nsbt57+3b3feSUO/MTrL7zj3nfPf83HPPfQxjNDjn6QDuAlACYDKAUgD0G33CowUAfZpCnw8YY/R9VIONZnZI8ZUAvgNg9gh5EaBaACMGNCIQMuVXqFZ6hDgi03YB2GjUOoZBcM43AEioPB/yQex1gXs9gCiCOZwwZU8As9n1ACUgJEfX0A2Cc05+vjfk6wrml4FBbP8cQwf3I/jZKfhPHQfv7QWYGWAhEZwDYgCmzGxY8gtgKb0R9ptugSW/cJhGqTLFSrkeq+gCwTmvAbBV7TqkfKDxMDxv/BnBYw3ggYCulYsQWSywlnwTzjsrYZ9FYRU13AAWMcbejMc4IYiQ+/xWtfTw/7sBA3+ohXCuOdZKGgJkykhFyq+fgq30Bq15cd0rLggtAOTrgzueh+/tvxpf+USwbDYkVdyN5PsfBExmNXVMIDFBcM4p51MMREbw8xb0b1iLYOu5ROqM6rm5sAhp67fAfM21aj41jLGX1T9qgggF8TF5DAgdF+BetRRi58VRKahnsjk7G6mbt8Iy5WtqcoqR6epgjwWClpqykTSEC21wr3kQYlenHh1GRUMA0n//Iky5UVYI821ijE2XC4kCoY4D7vejd8k9EC6cN6acEATLyIApJR2wWsHdLojd3YDFEpOPZIFNT8NSUJRI1gbG2MYwkQJEyI0UDj/wQi28f9mdiKn0nDYy64xZcMz5PmzXTwdLz1AmtT43AqdOwrf/Hfj/dRjc540812EBOS9yqzzGGP2FGsTOywUa7QnS8B9vRN/a5UAwcf635E/BuGVrYZ1WoivlBptP49K65RC6XDBgATmQiDUiILSs0LNgLkSXK74VuIjkmqVwVtWAxXEVLSa0OXrfeA2OW26NFwOx5EesIQdBFiBLSIN3v4vBF5bAdyQH3BuVs0NEHElV1Uh+YJkud7sKRJI15CAopdIZQBpCUwV4zzsQ+6zo310A0R1duCVV3YfkxQ9dBd10s6xjjJVLINSuxAf+A6GhDOCDEjcC4j2UC/8nw4Fqzs5BxkuvgqWk6pZ4lQgzwiAUriS2bofYvEYpkwHej3MwdDgH3MeQsvpXcNxecZX0MsS2JgyCKlQ6oYVcaR54z35NToHWVAwdvxlpT74O5nAYknaViGvDIA7Kj5fBj/KBodibG5u0HubC3+jWadEOL6wJ6+XE7GwW4IlKB1KTFMzeDIMYLjPEIQQPjlNvIQoJ5tK/g2XNSSyV4o1W5/FBWMYABPF68X4nCr9ikstuCYOg59Lg3jMQ6qfGAcFhnvUZmDP//w6CBD72YztuLlKULu5oEP0nITTQwSTG0nEOS3kvYCZrJR5jaQmStna+Hd+7Xll/RYMY+BTCEdou4oCY7QIsKYkRjLE7kcBfzLNj7je0QfSGzw7c2wKhvjC+O337LJh94pcC4tE77fhusTaI4cAWPAjWpcUP7JK3wMbP/VJAbF5gR1mBAkQksOkYSsfRK/vEoYnggdgnOHPeOrD8dbpBzNo8CJvO7BQvi4kceK7Gieu+qshOddqb3YlK8K63opRk4Djqn4A/svmonbMNTouuRhio5aRnNLUJWP2qL1Y0Ii3JhD8tdWCcQ7Eikc1OWXacewriWeVmRgBe8RZil6cI/dyETTOX4/Y8zV6RHn01aXZ/7MeOD2KfXaZda8K2aqd6bqTsoM41BfeVvWLwLIQjNwDcI33vFh3YNjANB/y5EQapjjTs/cF2pNqSR6y0fCK5yt3PeuDqj222hWVWLC63qeXlyUtxWenBITRVgve8jfNCEtZcugmtQvS+sLBoPn5eet+YgNjXGMD29/1xeT15jwM35ivONlLTQA6CunyRJi53HcAr9Q9jp6cIA9yqyVwER/XUu7Ci5N5RATnWIuCxvUO45I1thcwUhj3LkqJdibGX5SDIpSjVSpcinItY+P4v0dwX/w6EgPyseAEWF1fCTA1kg+PMRRGPvO6DayB+9FfMsOKh2zRcibErKTYSC5wrrHGk4wRWfbgFfjFxoyArORtby1bj61kFumD0+fvx0ol9eK8hF3B/K+6crBSGZ6qdyElTqLuLMbaIJqpBKKxBBE8f24nXTv9Nl2JWkxVl15Ri3uTZmJZViGxnpmKeJ+jDGXcrDrUfxYHWepz3XAS4GY6eStj67ggVKdGils6x4Sczo1yaWjaSm2g1zxTW8Al+VP/jEZzra9MFJEwkcBEZjjRk2tNA/w8EPXD53GAxvMbiLYazcwlYUNmrmjzBhB0PRKXV2M0zmVspmgat/e14uG4TOjxdhoAYJTb5c5HUsRKmQI40dXwqw++qHJiYpTo/MJYn5627oXxhsBM//ed6dHq6jepmiJ5xC+w9VcgO3Ibaex2YpASgv6F8JTtJt0ORPhT91tb/BVZ8uAXn+9sNKWaUeLwzExtLH8fMSdnqqT/SujWKW5ZxVbYijpSpnjuxG3tOv4sADxrVLy49XZ+VZE/FE2WrkJOUpaZVxEFCd5ITaAGh50c7PsGjR59B72DPmABxWByoua4CCwvv0CosYwLQzE5aGoVujci15G8HSKQftTdiz3/fQ2PXpxgS4pcNat78clE5JWUifph/K+bllyPNFnVapBhYqXU7ZMgSsoxFly5UX0UuX+SMmvvaUP9FExo6T+JMXyvaB7tghUlxBRwElwrGwvTJKM6cgpk5JZgxoRh2c9ROTKzpTQOKgYSvTeg8qgyrG8u91KscEIO46OmBJ+iFiZkkF0m3pyDZElX/qKfS6tfKL1ES+athEKHMRdagTTFyl5FIkI7nkvIAtoUvT3TMkUhGBELlYvRiCr0mEemo6xUeoqu73F+jj2Hlw3JGBUKVxcg6BIheFSJA9F0eP7TS9CFfD78utM/oqmst0P8Aeu5XWN2hKSMAAAAASUVORK5CYII="/> Login*/}
                      {/*    with Google</a>*/}
                  </div>
              </div>
              <div className={"divider"}></div>
          </footer>
      </div>
      </body>
      </html>
  );
}
