name: hiholive

on:
  push:
    branches:
      - deploy/admin-ui
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        working-directory: admin-ui
        run: npm ci

      - name: Build
        working-directory: admin-ui
        run: npm run build --if-present

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync ./admin-ui/dist s3://${{ secrets.ADMIN_UI_BUCKET }}/
      - name: Invalid Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.ADMIN_UI_DISTRIBUTION_ID }} --paths "/*"