name: film-ci
on:
  push:
    branches:
      - deploy/film-api
      - deploy/api
jobs:
  Build:
    name: Build &  Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle build
        run: ./gradlew build -p film
        working-directory: ./api

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/v2r1j0e6/ani4h-api-film:latest ./api/film
          docker push $ECR_REGISTRY/v2r1j0e6/ani4h-api-film:latest
  deploy:
    name: Build &  Deploy
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: deploy
        run: |
          aws ecs update-service --cluster ani4h-cluster --service film --force-new-deployment --region ap-southeast-1

